name: get_bilicoins

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: 0 1 * * *
  watch:
    types: started

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id

    steps:
    - uses: actions/checkout@v2
    - name: 初始化Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    
    - name: 执行程序
      run: |
          pip install -r requirements.txt
          account='${{secrets.ACCOUNT}}'
          password='${{secrets.PASSWORD}}'
         python daily_bonus.py <<EOF
          $account
          &password
        EOF
