on:
  schedule:
    - cron: 00 00 * * *

jobs:
  bilibili_job:
    runs-on: ubuntu-18.04
    if: github.event.repository.owner.id == github.event.sender.id  # 自己点的 start
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Main
        uses: ./
        env:
          account: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.PASSWORD }}

