on: [push]

jobs:
  bilibili_job:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout master
        uses: actions/checkout@v2
      - name: Main
        uses: ./
        env:
          account: ${{ secrets.ACCOUNT }}
          password: ${{ secrets.PASSWORD }}

